image: node:16 # Imagen de Node.js

# Definición de los estados del pipeline
stages:
  - build
  - test
  - doc
  - deploy

# Definición de los trabajos del pipeline

# Definición del trabajo de construcción
build_job:
  stage: build
  script:
    - echo "Instalando dependencias..."
    - npm install
  artifacts:
    paths:
      - node_modules/

# Definición del trabajo de prueba
test_job:
  stage: test
  script:
    - echo "Ejecutando pruebas..."
    - npm run test
  dependencies:
    - build_job

# Definición del trabajo de generación de documentación
doc_job:
  stage: doc
  script:
    - echo "Generando documentación..."
    - npm run docs
  artifacts:
    paths:
      - public/docs

# Definición del trabajo de despliegue de la aplicación
pages:
  stage: deploy
  script:
    - echo "Desplegando la aplicaciónen gitlab-pages..."
  artifacts:
    paths:
      - public
  only:
    - master
