name: Code Smells Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run Plato analysis
        run: npm run plato

      - name: Upload Plato report
        uses: actions/upload-artifact@v4
        with:
          # Poner el nombre del directorio donde se genera el informe de Plato
          name: src/github-actions/code-smells
          path: src/github-actions/code-smells