name: Code Smells Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Job to analyze code smells using Plato
  analyze-code-with-plato:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run Plato analysis
        run: npm run plato

      - name: Move Plato report to 'docs/code-smells'
        # Copiar el contenido del informe de Plato a la carpeta 'docs/code-smells'
        run: |
          mkdir -p docs/code-smells
          cp -r src/github-actions/code-smells/plato-report/* docs/code-smells/

      - name: Deploy GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_FRANCO }}
          publish_dir: docs