name: Example Github Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/github-actions/example-action

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Guarda node_modules como artefacto para otros jobs
      - name: Save node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: src/github-actions/example-action/node_modules