name: Example Github Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Guarda node_modules como artefacto para otros jobs
      - name: Save node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      
      # Añade node_modules/.bin al PATH
      # guardas node_modules como artefacto y luego lo descargas, esos symlinks no siempre sobreviven al proceso
      - name: Fix bin path
        run: echo "./node_modules/.bin" >> $GITHUB_PATH

      # Ejecuta los tests
      - name: Run tests
        run: npm run test-figures