name: Example Github Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Guarda node_modules como artefacto para otros jobs
      - name: Save node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: ../../src/example-action/node_modules

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

        # Descarga el artefacto node_modules del job "build"
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: ../../src/example-action/node_modules

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run tests
        run: npm test