name: Practices

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the index page
        run: npm start

      # Copia el reporte directamente a la carpeta 'docs' del repositorio
      - name: Move the page to docs/practices
        run: |
          mkdir -p docs/practices
          cp -r src/github-actions/practices/* docs/practices/

      # Despliega desde la carpeta 'docs' de la rama actual (master)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_FRANCO }}  # Usa el token por defecto
          publish_dir: docs
          keep_files: true