name: Testing and Coverage

concurrency:
  group: docs-deploy-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      # Copia el reporte directamente a la carpeta 'docs' del repositorio
      - name: Move coverage report to docs/testing-and-coverage
        run: |
          mkdir -p docs/testing-and-coverage
          cp -r src/github-actions/testing-and-coverage/coverage/lcov-report/* docs/testing-and-coverage/

      # Despliega desde la carpeta 'docs' de la rama actual (master)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_FRANCO }}  # Usa el token por defecto
          publish_dir: docs